import Head from 'next/head'
import Image from 'next/image'
import Header from '../Components/Header'
import Hero from '../Components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>gapeFrute</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Hero/>
    </div>
  )
}
